package com.rxnqst.pvz;

public enum GameObjectType {
    // * Plants
    Peashooter,
    Sunflower,
    Wallnut,
    PotatoMine,
    _PotatoMine_unready,
    SnowPeashooter,
    Puffshroom,
    CherryBomb,
    Cactus,
    CabbagePult,
    TriplePeashooter,
    WatermelonPult,
    IceMushroom,
    Jalapeno,
    Pumpkin,
    TallWallnut,
    SpikeRock,
    SpikeWeed,
    TorchWood,
    // * Plant seeds
    SeedsPeashooter,
    SeedsSunflower,
    SeedsWallnut,
    SeedsPotatoMine,
    SeedsSnowPeashooter,
    SeedsPuffshroom,
    SeedsCherryBomb,
    SeedsCactus,
    SeedsCabbagePult,
    SeedsTriplePeashooter,
    SeedsWatermelonPult,
    SeedsIceMushroom,
    SeedsJalapeno,
    SeedsPumpkin,
    SeedsTallWallnut,
    SeedsSpikeRock,
    SeedsSpikeWeed,
    SeedsTorchWood,
    // * Peas
    Pea,
    SnowPea,
    Needle,
    Watermelon,
    Cabbage,
    Puff,
    FirePea,
    FireNeedle,
    // * Zombies
    ZBasic,
    ZConehead,
    ZBuckethead,
    ZDoor,
    ZBalloon,
    ZYeti,
    ZImp,
    ZZomboni,
    ZJackbox,
    // * Zombie seeds
    ZSeedsBasic,
    ZSeedsConehead,
    ZSeedsBuckethead,
    ZSeedsDoor,
    ZSeedsBalloon,
    ZSeedsYeti,
    ZSeedsImp,
    ZSeedsZomboni,
    ZSeedsJackbox,
    // * Other objects
    ZGrave,
    ZGrave1,
    ZGrave2,
    ZSeedsGrave,
    ZSeedsFlag,
    ZFlag,
    // * Environment, UI, etc
    Bush_1,
    Bush_R,
    Field,
    BG,
    Fog,
    SeedInterface,
    ZombieInterface,
    ShovelIcon,
    // * Items
    Shovel,
    Sun
}
