compile:
	javac com/rxnqst/pvz/PvZ.java 
	jar cfe PvZ.jar com.rxnqst.pvz.PvZ com/rxnqst/pvz/*.class com/rxnqst/pvz/plants/attackFamily/*.class com/rxnqst/pvz/plants/helpFamily/*.class com/rxnqst/pvz/plants/defenceFamily/*.class com/rxnqst/pvz/plants/boomFamily/*.class com/rxnqst/pvz/gui/*.class com/rxnqst/pvz/plants/*.class com/rxnqst/pvz/zombies/*.class com/rxnqst/pvz/utils/*.class com/rxnqst/pvz/net/*.class com/rxnqst/pvz/peas/*.class com/rxnqst/pvz/threads/*.class com/rxnqst/pvz/effects/*.class
	del /q "com\rxnqst\pvz\*.class"
	del /q "com\rxnqst\pvz\gui\*.class"
	del /q "com\rxnqst\pvz\plants\*.class"
	del /q "com\rxnqst\pvz\zombies\*.class"
	del /q "com\rxnqst\pvz\utils\*.class"
	del /q "com\rxnqst\pvz\net\*.class"
	del /q "com\rxnqst\pvz\dataIO\*.class"
	del /q "com\rxnqst\pvz\peas\*.class"
	del /q "com\rxnqst\pvz\threads\*.class"
	del /q "com\rxnqst\pvz\effects\*.class"
	del /q "com\rxnqst\pvz\plants\attackFamily\*.class"
	del /q "com\rxnqst\pvz\plants\boomFamily\*.class"
	del /q "com\rxnqst\pvz\plants\defenceFamily\*.class"
	del /q "com\rxnqst\pvz\plants\helpFamily\*.class"
	copy PvZ.jar "C:\Users\Rxnqst\Desktop\Plants vs Zombies\"
	explorer "C:\Users\Rxnqst\Desktop\Plants vs Zombies\"
	cls